ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'ADMIN';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'AREA_SALES_OFFICER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'CASHIER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'SECURITY_OFFICER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'SERVICE_ADVISOR';

ALTER TABLE "User" ALTER COLUMN "role" DROP NOT NULL;
